version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Exposes the Next.js app on port 3000
    restart: always # Ensures the container restarts if it crashes
    environment:
      - NODE_ENV=production # Set to production mode
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
