export  enum ErrorMessage {
// 400: Bad Request Errors
INVALID_INPUT = "INVALID_INPUT",
MISSING_FIELDS = "MISSING_FIELDS",
VALIDATION_ERROR = "VALIDATION_ERROR",

// 401: Unauthorized Errors
UNAUTHORIZED = "UNAUTHORIZED",
TOKEN_EXPIRED = "TOKEN_EXPIRED",

// 403: Forbidden Errors
FORBIDDEN = "FORBIDDEN",
ACCESS_DENIED = "ACCESS_DENIED",

// 404: Not Found Errors
NOT_FOUND = "NOT_FOUND",
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

// 409: Conflict Errors
DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
CONFLICT = "CONFLICT",

// 500: Internal Server Errors
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
DATABASE_ERROR = "DATABASE_ERROR",
UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
}
