#!usr/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Please run "npm run format", add changes, and try committing again.'
    false;
)

# Check ESLint standards
npm run check-lint ||
(
    echo '😤 ESLint Check Failed. Make the required changes listed above, add them, and try committing again.'
    false;
)

# Check TypeScript standards
npm run check-types ||
(
    echo '🤡 TypeScript check failed. Fix the type issues and try committing again.'
    false;
)

# Build check
npm run build ||
(
    echo '❌ Build failed! Please address the build issues before committing.'
    false;
)

# If everything passes...
echo '✅ All checks passed. Committing your changes now! ✅'
