name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy  # Trigger the workflow on push to the deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH access to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Copy project files from git hub action runner to the server
      - name: Copy Project Files to Server
        run: |
          rsync -avz --exclude='.git' ./ deploy@${{ secrets.IP_ADDRESS }}:/home/deploy/nextjs-app/

      # Deploy the application to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.IP_ADDRESS }} << EOF
            cd ..
            cd home/deploy/project
            git checkout deploy
            git pull origin deploy
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
